CREATE TABLE Billett
(
    id INTEGER AUTO_INCREMENT NOT NULL,
    film VARCHAR(30) NOT NULL,
    antall VARCHAR(4) NOT NULL,
    fornavn VARCHAR(30) NOT NULL,
    etternavn VARCHAR(30) NOT NULL,
    telefonnr VARCHAR(20) NOT NULL,
    epost VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
);